name: jovial_misc_native
description: Library split off from jovial_misc to make it clear that the rest of jovial_misc works on the JS runtime.
version: 0.8.1
homepage: https://bill.jovial.com/

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
    jovial_misc: ^0.8.1
    pointycastle: ^3.1.0
    intl: ^0.18.0
    async: ^2.5.0
    collection: ^1.14.11
    convert: ^3.0.0

dev_dependencies:
  test: ^1.16.6
  lints: ^1.0.1

repository: https://github.com/zathras/misc/tree/master/dart/jovial_misc_native

issues: https://github.com/zathras/misc/issues
